#SPDX-License-Identifier: MIT-0
---
# tasks file for lx-comp


## Add task to print /etc/issue.net


- name: Print /etc/issue.net
  ansible.builtin.command: cat /etc/issue.net
  register: issue_net_output

- name: Display /etc/issue.net output
  ansible.builtin.debug:
    msg: "Contents of /etc/issue.net:\n{{ issue_net_output.stdout }}"