---
# handlers file for roles/rhel_compliance


# - name: Update_Crypto_Policy
#   ansible.builtin.set_fact:
#     rhel8cis_full_crypto_policy: "{{ rhel8cis_crypto_policy }}{{ rhel8cis_crypto_policy_module }}{% if rhel8cis_additional_crypto_policy_module | length > 0 %}:{{ rhel8cis_additional_crypto_policy_module }}{% endif %}"
#   notify: Set_Crypto_Policy

# - name: Set_Crypto_Policy
#   when: prelim_system_wide_crypto_policy.stdout != rhel8cis_full_crypto_policy
#   ansible.builtin.command: update-crypto-policies --set "{{ rhel8cis_full_crypto_policy }}"
#   changed_when: true
#   notify:
#     - Set_reboot_required
#     - Restart_sshd


# - name: Update_Crypto_Policy
#   ansible.builtin.set_fact:
#     rhel8cis_full_crypto_policy: >-
#       {{
#         (rhel8cis_crypto_policy | default('DEFAULT', true))
#         ~ (
#             ':' ~ (rhel8cis_crypto_policy_module.stdout | default(rhel8cis_crypto_policy_module | default('', true), true) | trim)
#             if ((rhel8cis_crypto_policy_module.stdout | default(rhel8cis_crypto_policy_module | default('', true), true) | trim) | length > 0)
#             else ''
#           )
#         ~ (
#             ':' ~ (rhel8cis_additional_crypto_policy_module | default('', true) | trim)
#             if ((rhel8cis_additional_crypto_policy_module | default('', true) | trim) | length > 0)
#             else ''
#           )
#       }}
#   notify: Set_Crypto_Policy

# - name: Set_Crypto_Policy
#   when: init_system_wide_crypto_policy.stdout != rhel8cis_full_crypto_policy
#   ansible.builtin.command: update-crypto-policies --set "{{ rhel8cis_full_crypto_policy }}"
#   changed_when: true
#   notify:
#     - Set_reboot_required
#     #- Restart_sshd



- name: Set_Crypto_Policy
  when: init_system_wide_crypto_policy.stdout != rhel8cis_crypto_policy_module
  ansible.builtin.command: update-crypto-policies --set "{{ rhel8cis_crypto_policy_module }}"
  changed_when: true
  notify:
    - Set_reboot_required
    - Restart_sshd

- name: Set_reboot_required
  ansible.builtin.set_fact:
    change_requires_reboot: true

- name: Restart_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted    