---
- name: "Copy patch {{ patch_item.patch_id }} to stage directory"
  block:

    - name: "Copy {{ patch_item.patch_zip }} to {{ patch_stage_dir }}"
      ansible.builtin.copy:
        src: "{{ patch_src_dir }}/{{ patch_item.patch_zip }}"
        dest: "{{ patch_stage_dir }}/{{ patch_item.patch_zip }}"
        #owner: "{{ oracle_user }}"
        #group: "{{ oracle_group }}"
        #mode: "0644"

    - name: "Confirm {{ patch_item.patch_zip }} copied"
      ansible.builtin.debug:
        msg: "Copied: {{ patch_item.patch_zip }} -> {{ patch_stage_dir }}/{{ patch_item.patch_zip }}"

  tags:
    - ohs_patch
    - copy
    - copy_patch
    - patches
