---
# roles/flaskapp/meta/main.yml

galaxy_info:
  role_name:    flaskapp
  author:       iam-middleware
  description:  "Production Flask app deployment on RHEL with gunicorn, nginx, systemd"
  company:      "LA Care Health Plan"
  license:      MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - flask
    - python
    - gunicorn
    - nginx
    - systemd
    - rhel

dependencies: []
