---
- name: Backup existing audit configuration
  block:
    - name: Check if auditd.conf exists
      ansible.builtin.stat:
        path: /etc/audit/auditd.conf
      register: auditd_conf_stat

    - name: Take backup of auditd.conf if it exists
      ansible.builtin.copy:
        src: /etc/audit/auditd.conf
        dest: "{{ audit_backup_dir }}/auditd.conf"
        remote_src: true
      when: auditd_conf_stat.stat.exists

    - name: Check if audit.rules dir exists
      ansible.builtin.stat:
        path: /etc/audit/rules.d
      register: audit_rules_dir_stat

    - name: Copy existing audit.rules to backup directory if it exists
      ansible.builtin.copy:
        src: /etc/audit/audit.rules
        dest: "{{ audit_backup_dir }}/audit.rules"
        remote_src: true
      when: audit_rules_dir_stat.stat.exists

    - name: take backup of plugins.d if it exists
      ansible.builtin.copy:
        src: /etc/audit/plugins.d
        dest: "{{ audit_backup_dir }}/plugins.d"
        remote_src: true
      when: audit_plugins_dir_stat.stat.exists
