---
# =============================================================================
# Role Tasks: audit_log_enrichment
# =============================================================================


- name: Include tasks to create necessary directories
  ansible.builtin.import_tasks: create_dirs.yml
  tags: [audit, dirs]

- name: Include tasks to backup existing audit configuration
  ansible.builtin.import_tasks: backup_audit.yml
  tags: [audit, backup]  

- name: Include tasks to ec2 metadata
  ansible.builtin.import_tasks: ec2-metadata.yml
  tags: [audit, ec2]



- name: Include package installation tasks
  ansible.builtin.import_tasks: packages.yml
  tags: [audit, packages]

- name: Include auditd configuration tasks
  ansible.builtin.import_tasks: auditd.yml
  tags: [audit, auditd]

# - name: Include audit rules tasks
#   ansible.builtin.import_tasks: audit_rules.yml
#   tags: [audit, rules]

# - name: Include audisp enrichment plugin tasks
#   ansible.builtin.import_tasks: audisp.yml
#   tags: [audit, audisp]

# - name: Include rsyslog EC2 enrichment tasks
#   ansible.builtin.import_tasks: rsyslog.yml
#   tags: [audit, rsyslog]

# - name: Include CloudWatch Logs agent tasks
#   ansible.builtin.import_tasks: cloudwatch.yml
#   when: cloudwatch_enabled | bool
#   tags: [audit, cloudwatch]

# - name: Include S3 log shipping tasks
#   ansible.builtin.import_tasks: s3_ship.yml
#   when: audit_s3_bucket | length > 0
#   tags: [audit, s3]
