- name: "CIS 1.2.2.1 | Check for available package updates"
  block:
    - name: "CIS 1.2.2.1 | Get available package updates"
      ansible.builtin.command:
        cmd: dnf -q check-update
      register: dnf_updates
      changed_when: false
      failed_when: false 

    - name: "CIS 1.2.2.1 | Display available updates"
      ansible.builtin.debug:
        msg: "{{ dnf_updates.stdout_lines }}"
      when: dnf_updates.rc == 100



- name: "CIS 1.2.2.1 | Install all available package updates"
  block:
    - name: "CIS 1.2.2.1 | Apply all available package updates"
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      register: patch_result

    - name: "CIS 1.2.2.1 | Display patch result"
      ansible.builtin.debug:
        msg: "patch status : {{ 'UPDATED' if patch_result.changed else 'ALREADY UP TO DATE' }}"

    - name: "CIS 1.2.2.1 | Reboot server to apply patches"
      ansible.builtin.reboot:
        msg: "Rebooting to apply package updates"
        reboot_timeout: 600
      when: patch_result.changed
  when: dnf_updates.rc == 100


- name: "CIS 2.4.1.7 | Verify /etc/cron.d permissions"
  block:
    - name: "CIS 2.4.1.7 | Stat /etc/cron.d"
      ansible.builtin.stat:
        path: /etc/cron.d
      register: cron_d_stat

    - name: "CIS 2.4.1.7 | Display /etc/cron.d permissions"
      ansible.builtin.debug:
        msg:
          - "Path: /etc/cron.d"
          - "Owner: {{ cron_d_stat.stat.pw_name }}"
          - "Group: {{ cron_d_stat.stat.gr_name }}"
          - "Mode: {{ cron_d_stat.stat.mode }}"