


#### 1.6.2 Ensure system wide crypto policy disables sha1 hash and signature support


- name: "Block: Get current crypto policy modules"
  block:
    - name: "Get current crypto policy modules"
      ansible.builtin.command: update-crypto-policies --show
      register: current_crypto_policy
      changed_when: false
      failed_when: false

    - name: "Debug: current_crypto_policy"
      ansible.builtin.debug:
        msg: "current_crypto_policy: {{ (current_crypto_policy.stdout | default('')) | trim }}"

  

# - name: "1.6.2 | PATCH | Ensure system wide crypto policy disables sha1 hash and signature support"
#   when:
#     - rhel8cis_rule_1_6_2
#     - "'NO-SHA1' not in rhel8cis_crypto_policy_module"
#   tags:
#     - level1-server
#     - level1-workstation
#     - automated
#     - patch
#     - crypto
#     - NIST800-53R5_SC-8
#     - rule_1.6.2
#   block:

  
#     - name: "1.6.2 | PATCH | Ensure system wide crypto policy disables sha1 hash and signature support"
#       ansible.builtin.template:
#         src: etc/crypto-policies/policies/modules/NO-SHA1.pmod.j2
#         dest: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
#         owner: root
#         group: root
#         mode: 'u-x,g-wx,o-rwx'
#       register: discovered_no_sha1_template

#     - name: "1.6.2 | PATCH | Ensure system wide crypto policy disables sha1 hash and signature support | submodule to crypto policy modules"
#       ansible.builtin.set_fact:
#         rhel8cis_crypto_policy_module: "{{ rhel8cis_crypto_policy_module + ':' + 'NO-SHA1' }}"
#       changed_when: discovered_no_sha1_template is changed # noqa: no-handler
#       notify:
#         - Update_Crypto_Policy
#         - Set_Crypto_Policy